# .github/workflows/review.yml
name: AI Code Review
on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]
jobs:
  review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '/pilot-review'))
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: ReviewPilot Action
        uses: prdai/review-pilot@v2.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          apiKey: ${{ secrets.GEMINI_API_KEY }}
          level: 'HIGH'
          customInstructionUri: 'https://raw.githubusercontent.com/guiodic/material-decoration/main/review-guide.txt'
